import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Calculator, CircleHelp, MessageCircle } from 'lucide-react';
import { legalConfig } from '@/data/config';
import { supabase } from '@/lib/supabase';

type CalculatorType = 'salary' | 'hire' | 'severance' | 'retirement' | 'overtime';
type Props = { type: CalculatorType; title: string; description: string };
const format = (value: number) => new Intl.NumberFormat('fa-IR').format(Math.max(0, Math.round(value)));

type SalarySettings = {
  year?: string; baseSalaryDaily?: number; housingAllowanceMonthly?: number; foodAllowanceMonthly?: number;
  insuranceEmployeeRate?: number; insuranceEmployerRate?: number; annualTaxFree?: number;
};

export default function CalculatorPage({ type, title, description }: Props) {
  const [salary, setSalary] = useState(120000000); const [days, setDays] = useState(30); const [years, setYears] = useState(3); const [hours, setHours] = useState(10); const [age, setAge] = useState(35); const [insuredYears, setInsuredYears] = useState(8); const [calculated, setCalculated] = useState(false);
  const [cfg, setCfg] = useState(legalConfig);
  useEffect(() => { let active = true; supabase.from('settings').select('value').eq('key', 'salary_1405').maybeSingle().then(({ data }) => { if (!active || !data) return; const s = data.value as SalarySettings; setCfg({ year: s.year ?? legalConfig.year, baseSalaryDaily: s.baseSalaryDaily ?? legalConfig.baseSalaryDaily, housingAllowanceMonthly: s.housingAllowanceMonthly ?? legalConfig.housingAllowanceMonthly, foodAllowanceMonthly: s.foodAllowanceMonthly ?? legalConfig.foodAllowanceMonthly, insuranceEmployeeRate: s.insuranceEmployeeRate ?? legalConfig.insuranceEmployeeRate, insuranceEmployerRate: s.insuranceEmployerRate ?? legalConfig.insuranceEmployerRate, annualTaxFree: s.annualTaxFree ?? legalConfig.annualTaxFree, taxBrackets: legalConfig.taxBrackets }); }); return () => { active = false; }; }, []);
  const result = useMemo(() => { const insurance = salary * cfg.insuranceEmployeeRate; const tax = Math.max(0, salary * 12 - cfg.annualTaxFree) * 0.1 / 12; if (type === 'salary') return salary + cfg.housingAllowanceMonthly + cfg.foodAllowanceMonthly - insurance - tax; if (type === 'hire') return salary * (1 + cfg.insuranceEmployerRate); if (type === 'severance') return salary / 30 * days * years; if (type === 'overtime') return salary / 220 * 1.4 * hours; return Math.max(0, age + insuredYears >= 60 ? salary * 0.9 : salary * 0.6); }, [type, salary, days, years, hours, age, insuredYears, cfg]);
  const salaryPart = type === 'salary' ? Math.max(10, Math.min(80, (salary / 300000000) * 100)) : 60; const insurancePart = type === 'salary' ? 7 : 20; const taxPart = Math.max(5, 100 - salaryPart - insurancePart);
  const range = (label: string, value: number, setValue: (value: number) => void, min: number, max: number, step: number) => <label className="range-field">{label}<strong>{format(value)}</strong><input type="range" min={min} max={max} step={step} value={value} onChange={(event) => { setValue(Number(event.target.value)); setCalculated(false); }} /><input type="number" value={value} onChange={(event) => { setValue(Number(event.target.value)); setCalculated(false); }} /></label>;
  const faqData: Record<CalculatorType, { intro: string; faqs: [string, string][] }> = {
    salary: { intro: 'اضافه‌کاری هر ساعت ۴۰٪ بالاتر از مزد عادی است (ماده ۵۹ قانون کار). کسورات شامل بیمه ۷٪ سهم کارگر و مالیات بر اساس پلکان معافیت سالانه محاسبه می‌شود.', faqs: [['بیمه سهم کارگر چند درصد است؟', '۷ درصد از مزد پایه به‌عنوان سهم بیمه کارگر کسر می‌شود (ماده ۳۷ قانون تأمین اجتماعی).'], ['مالیات چگونه محاسبه می‌شود؟', 'بر اساس پلکان معافیت سالانه؛ سقف معافیت ۱۴۰۵ معادل ۲۸۸ میلیون تومان است و نرخ‌های ۱۰ تا ۳۰ درصد پلکانی اعمال می‌شود.'], ['اضافه‌کاری چه نرخی دارد؟', 'هر ساعت اضافه‌کاری معادل ۱۴۰٪ مزد عادی ساعتی است (ماده ۵۹ قانون کار).']] },
    severance: { intro: 'سنوات پایان خدمت به هر علت از جمله استعفا تعلق می‌گیرد (ماده ۲۴ قانون کار: «به هر علت»). سنوات مشمول کسر بیمه نیست و فرمول آن: هر سال سابقه معادل یک ماه آخرین مزد.', faqs: [['با استعفا هم سنوات می‌گیرم؟', 'بله، ماده ۲۴ قانون کار صراحتاً بیان می‌کند سنوات «به هر علت» تعلق می‌گیرد.'], ['سنوات مشمول کسر بیمه است؟', 'خیر، سنوات پایان خدمت مشمول کسر بیمه تأمین اجتماعی نیست.'], ['فرمول محاسبه سنوات چیست؟', 'هر سال سابقه کار معادل یک ماه آخرین مزد پایه است.']] },
    retirement: { intro: 'مسیرهای بازنشستگی شامل ۶۰ سال سن با ۲۰ سال سابقه، هر سن با ۳۰ سال سابقه، یا ۳۵ سال سابقه بدون شرط سن است (ماده ۷۶). مستمری از متوسط ۹۰ روز آخر × ۱/۳۰ به ازای هر سال سابقه محاسبه می‌شود (ماده ۷۷). کارهای سخت و زیان‌آور: ۲۰ سال متوالی یا ۲۵ سال متناوب بدون شرط سن.', faqs: [['شرط سن بازنشستگی چیست؟', '۶۰ سال سن با حداقل ۲۰ سال سابقه، یا بدون شرط سن با ۳۵ سال سابقه (ماده ۷۶).'], ['مستمری چگونه محاسبه می‌شود؟', 'متوسط ۹۰ روز آخر مزد × ۳۰/۱ به ازای هر سال سابقه بیمه (ماده ۷۷).'], ['کارهای سخت و زیان‌آور چه شرطی دارند؟', '۲۰ سال متوالی یا ۲۵ سال متناوب سابقه بدون شرط سن کافی است.']] },
    hire: { intro: 'بیمه بیکاری ۳٪ بر دوش کارفرماست. فرمول سرانگشتی هزینه واقعی استخدام: پایه حقوق × ۱٫۳۵ تا ۱٫۴ شامل سهم بیمه کارفرما ۲۳٪، بیمه بیکاری ۳٪ و مزایا.', faqs: [['بیمه بیکاری چند درصد است؟', '۳ درصد از مزد که تماماً بر عهده کارفرماست.'], ['هزینه واقعی استخدام چقدر است؟', 'تقریباً ۱٫۳۵ تا ۱٫۴ برابر مزد پایه، شامل سهم بیمه کارفرما و مزایای قانونی.'], ['سهم بیمه کارفرما چند درصد است؟', '۲۳ درصد از مزد پایه به‌عنوان سهم بیمه تأمین اجتماعی کارفرما.']] },
    overtime: { intro: 'اضافه‌کاری هر ساعت ۴۰٪ بالاتر از مزد عادی محاسبه می‌شود (ماده ۵۹ قانون کار). مزد ساعتی از تقسیم مزد ماهانه بر ۲۲۰ ساعت به‌دست می‌آید.', faqs: [['نرخ اضافه‌کاری چیست؟', 'هر ساعت اضافه‌کاری معادل ۱۴۰٪ مزد عادی ساعتی است (ماده ۵۹).'], ['مزد ساعتی چگونه محاسبه می‌شود؟', 'مزد ماهانه تقسیم بر ۲۲۰ ساعت کار استاندارد ماهانه.'], ['حداکثر اضافه‌کاری مجاز چقدر است؟', 'حداکثر ۴۴ ساعت اضافه‌کاری در ماه با رعایت شرط‌های قانون کار مجاز است.']] },
  };
  const content = faqData[type];
  return <section className="inner-page calculator-page"><div className="container calc-layout"><div className="calc-copy"><span className="eyebrow">ابزارهای کاربان · قانون کار {cfg.year}</span><h1>{title}</h1><p className="lead">{description}</p><div className="education"><h2>قبل از محاسبه بدانید</h2><p>{content.intro}</p></div><div className="faq"><h2>پرسش‌های متداول</h2>{content.faqs.map(([q, a]) => <details key={q}><summary>{q}<CircleHelp size={16} /></summary><p>{a}</p></details>)}</div></div><div className="calculator-card"><div className="calc-card-head"><Calculator /><span>محاسبه‌گر {cfg.year}</span></div>{range('حقوق یا درآمد ماهانه (تومان)', salary, setSalary, 30000000, 300000000, 1000000)}{type === 'severance' && <>{range('روزهای کارکرد', days, setDays, 1, 31, 1)}{range('سابقه (سال)', years, setYears, 1, 30, 1)}</>}{type === 'overtime' && range('ساعات اضافه‌کاری', hours, setHours, 1, 100, 1)}{type === 'retirement' && <>{range('سن فعلی', age, setAge, 18, 70, 1)}{range('سابقه بیمه (سال)', insuredYears, setInsuredYears, 1, 40, 1)}</>}{type === 'salary' && <div className="calc-hints"><span>سهم بیمه کارمند: ۷٪</span><span>سهم بیمه کارفرما: ۲۳٪</span></div>}<button className="button full-button calculate-button" type="button" onClick={() => setCalculated(true)}>محاسبه نتیجه <ArrowLeft size={17} /></button><div className={`result-layout ${calculated ? 'result-visible' : ''}`}><div className="pie-chart" style={{ background: `conic-gradient(#0F5132 0 ${salaryPart}%, #C9A227 ${salaryPart}% ${salaryPart + insurancePart}%, #12344D ${salaryPart + insurancePart}% 100%)` }} /><div className="result-box"><span>برآورد شما</span><strong>{format(result)} <small>تومان</small></strong><div className="result-legend"><span><i className="legend-salary" />حقوق</span><span><i className="legend-insurance" />بیمه</span><span><i className="legend-tax" />مالیات</span></div></div></div><a className="button full-button" href="/خدمات">مشاوره مرتبط <MessageCircle size={17} /></a></div></div></section>;
}
